# Bun configuration for the project
[install]
# Trust all packages by default for development speed
trust = true

[test]
# Use bun:test as the test runner
runner = "bun"

# Preload setup file before tests
preload = ["./tests/setup.ts"]

# Test file patterns
include = [
  "tests/**/*.test.ts",
]

# Exclude patterns
exclude = [
  "node_modules",
  "dist",
  "build",
]

# Test timeout in milliseconds (30 seconds)
timeout = 30000

# Use single-threaded execution for database operations
# This ensures tests don't interfere with each other
threads = 1

# Enable source maps for better error messages
sourcemap = "inline"

# Environment variables for testing
[test.env]
NODE_ENV = "test"
LOG_LEVEL = "error"
